function [pesosC,cmdout] = Compute_matrixs_general_mp(Settings,Index_OperadorXPesos,Npesos)
 pesosC = cell([Npesos, length(Index_OperadorXPesos)]);
     Parametros = sprintf(' %10.50f',Settings.Params);
     OperadoresIndex = ['"',sprintf('%d ',Index_OperadorXPesos),'"'];

     command = char(strcat('./',Settings.programa,...
         {' '} ,'./',num2str(Settings.lib),...
         {' '} ,num2str(Settings.presicion),...
         {' '} ,Settings.file_indices_1,...
         {' '} ,Settings.file_indices_2,...
         {' '} ,Settings.file_indices_3,...
         {' '} ,Settings.file_distance,...
         {' '} ,Settings.file_psc,...
         {' '} ,Settings.file_pfc,...
         {' '} ,num2str(Settings.NOperadoresX),...
         {' '} ,num2str(Settings.NOperadoresY),...
         {' '} ,OperadoresIndex,...
         {' '} ,num2str(Npesos) ...
         ));
     
     [status,cmdout] = system([command,Parametros]);
     
     Pesos_string = textscan(cmdout,'%s','Delimiter','\n');
     for k=1:length(Index_OperadorXPesos)
     for i=1:Npesos
         aux = textscan(Pesos_string{1}{i+(k-1)*Npesos},'%s');
         auxarray = mp(zeros(1,length(aux{1})));
         for sk=1:length(aux{1})
             auxarray(sk) = mp(aux{1}{sk});
         end
         pesosC(i,k) = {auxarray};
     end
     end
     
 end