function Compute_matrixs_general_saveV2(Settings,FilesDir,dir_name,Index_OperadorXPesos,Npesos)

     Parametros = sprintf(' %f',Settings.Params);
     OperadoresIndex = ['"',sprintf('%d ',Index_OperadorXPesos),'"'];

     command = char(strcat('./',Settings.programa,...
         {' '} ,'./',num2str(Settings.lib),...
         {' '} ,num2str(Settings.presicion),...
         {' '} ,FilesDir.file_indices_1,...
         {' '} ,FilesDir.file_indices_2,...
         {' '} ,FilesDir.file_indices_3,...
         {' '} ,FilesDir.file_distance,...
         {' '} ,FilesDir.file_psc,...
         {' '} ,FilesDir.file_pfc,...
         {' '} ,num2str(Settings.NOperadoresX),...
         {' '} ,num2str(Settings.NOperadoresY),...
         {' '} ,OperadoresIndex,...
         {' '} ,num2str(Npesos), ...
         {' '} ,dir_name,...
         {' '} ,num2str(Settings.Coutpresicion)...
         ));
     
        system([command,Parametros],'-echo');
     
     
 end